name: Build AX3000T OpenWrt WG Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Clone official OpenWrt source
      run: |
        git clone --depth=1 --branch v23.05.5 https://git.openwrt.org/openwrt/openwrt.git openwrt
        cp $GITHUB_WORKSPACE/openwrt-config-wireguard openwrt/.config

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
        python3-distutils rsync unzip zlib1g-dev file wget

    - name: Update and install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig

    - name: Build firmware
      run: |
        cd openwrt
        make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-AX3000T-WireGuard
        path: openwrt/bin/targets/
